name: 'Doxygen Azure Blob Storage Deploy Action'
author: 'Darren Perry'
description: 'Make docs with Doxygen then deploy the generated HTML to Azure Blob Storage'
branding:
  icon: "upload-cloud"
  color: "purple"

inputs:
  azure_blob_connection_string:
    description: 'Azure Access Keys Connection string. https://learn.microsoft.com/en-gb/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#regenerate-access-keys'
    required: true
  project_name:
    description: 'The title of the project documentation.'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      name: Checkout repository
      with:
        submodules: "true"

    - name: Get Doxyfile
      run: wget https://borndevdocumentation.z33.web.core.windows.net/Doxyfile
      shell: bash

    - name: Install Doxygen
      run: sudo apt-get install doxygen graphviz -y
      shell: bash

    - name: Generate Doxygen Documentation
      run: PROJECT_NAME="${{ inputs.project_name }}" doxygen
      shell: bash

    - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      name: Uploading to Azure storage...
      with:
        connection_string: ${{ inputs.azure_blob_connection_string }}
        container_name: "$web"
        source_folder: "Docs"
        destination_folder: ${{ github.event.repository.name }}
        clean_destination_folder: true
        delete_if_exists: true